#!/usr/bin/env python3
"""Annotate FineBio FPV trials: when a bench copilot should interrupt, and what it says.

One JSON object per video. Timing is taken from the trial's action-step file.
Wording is generated by Qwen2.5-VL-72B from the protocol, the timed actions,
and a few first-person frames at the step boundaries.
"""

from __future__ import annotations

import argparse
import csv
import json
import re
import traceback
from pathlib import Path

import cv2
import torch
from PIL import Image
from qwen_vl_utils import process_vision_info
from transformers import AutoProcessor, Qwen2_5_VLForConditionalGeneration

PROTOCOL_NAMES = {
    1: "Cell lysate collection (single PBS wash)",
    2: "Cell lysate collection (double PBS wash)",
    3: "Magnetic-bead DNA extraction (single ethanol wash)",
    4: "Magnetic-bead DNA extraction (double ethanol wash)",
    5: "PCR reaction setup with 8-tube strips",
    6: "Spin-column DNA extraction (two wash steps)",
    7: "Spin-column DNA extraction (three wash steps)",
}

# Majority step order across FineBio trials of each protocol.
CANONICAL = {
    1: [
        "remove_culture_medium",
        "add_pbs",
        "shake_plate",
        "aspirate_pbs",
        "add_cell_lystate",
        "shake_plate",
        "transfer_cell_lystate_to_tube",
        "spindown",
        "aspirate_supernatant",
    ],
    2: [
        "remove_culture_medium",
        "add_pbs",
        "shake_plate",
        "aspirate_pbs",
        "add_pbs",
        "shake_plate",
        "aspirate_pbs",
        "add_cell_lystate",
        "shake_plate",
        "transfer_cell_lystate_to_tube",
        "spindown",
        "aspirate_supernatant",
    ],
    3: [
        "add_magnetic_beads",
        "pipetting",
        "pipetting",
        "vortex",
        "spindown",
        "place_in_magnetic_rack",
        "aspirate_supernatant",
        "add_wash_buffer",
        "pipetting",
        "vortex",
        "spindown",
        "place_in_magnetic_rack",
        "aspirate_supernatant",
        "add_70pct_ethanol",
        "pipetting",
        "vortex",
        "spindown",
        "place_in_magnetic_rack",
        "aspirate_supernatant",
        "add_sterile_water",
        "pipetting",
        "vortex",
        "spindown",
        "place_in_magnetic_rack",
        "transfer_supernatant_to_empty_tube",
    ],
    4: [
        "add_magnetic_beads",
        "pipetting",
        "pipetting",
        "vortex",
        "spindown",
        "place_in_magnetic_rack",
        "aspirate_supernatant",
        "add_wash_buffer",
        "pipetting",
        "vortex",
        "spindown",
        "place_in_magnetic_rack",
        "aspirate_supernatant",
        "add_70pct_ethanol",
        "pipetting",
        "vortex",
        "spindown",
        "place_in_magnetic_rack",
        "aspirate_supernatant",
        "add_70pct_ethanol",
        "pipetting",
        "vortex",
        "spindown",
        "place_in_magnetic_rack",
        "aspirate_supernatant",
        "add_sterile_water",
        "pipetting",
        "vortex",
        "spindown",
        "place_in_magnetic_rack",
        "transfer_supernatant_to_empty_tube",
    ],
    5: [
        "transfer_sample_to_8_tube_stripes",
        "transfer_pcrmix_to_8_tube_stripes",
        "transfer_forward_primer_to_8_tube_stripes",
        "transfer_reverse_primer_to_8_tube_stripes",
        "transfer_template_dna_to_8_tube_stripes",
        "transfer_water_to_8_tube_stripes",
        "close_8_tube_stripes_lid",
        "vortex_8_tube_stripes",
        "spindown_8_tube_stripes",
        "load_8_tube_stripes_to_pcr_machine",
    ],
    6: [
        "add_binding_buffer",
        "add_70pct_ethanol",
        "vortex",
        "spindown",
        "transfer_sample_tube_to_spin_column_tube",
        "spindown",
        "dispense_solution",
        "add_wash_buffer",
        "spindown",
        "dispense_solution",
        "add_wash_buffer",
        "spindown",
        "dispense_solution",
        "detach_spin_column_and_insert_to_new_tube",
        "add_extract",
        "spindown",
        "dispense_spin_column",
    ],
    7: [
        "add_binding_buffer",
        "add_70pct_ethanol",
        "vortex",
        "spindown",
        "transfer_sample_tube_to_spin_column_tube",
        "spindown",
        "dispense_solution",
        "add_wash_buffer",
        "spindown",
        "dispense_solution",
        "add_wash_buffer",
        "spindown",
        "dispense_solution",
        "add_wash_buffer",
        "spindown",
        "dispense_solution",
        "detach_spin_column_and_insert_to_new_tube",
        "add_extract",
        "spindown",
        "dispense_spin_column",
    ],
}

TECHNIQUE = {
    "remove_culture_medium": "Tilt the plate and aspirate spent medium from the side of the well. Do not scrape the monolayer. Discard that tip; it is now contaminated with medium.",
    "add_pbs": "Dispense PBS down the wall of the well, not onto the cells. Use a fresh tip. Say which wash this is (first or second) from the step index.",
    "shake_plate": "Rock the closed plate gently so the liquid covers the monolayer. Do not swirl hard enough to splash or detach cells. If this shake follows lysis buffer, say it is to spread lysis buffer, not PBS.",
    "aspirate_pbs": "Aspirate PBS from the edge until the well is dry. Residual PBS dilutes the lysis buffer. Discard the tip.",
    "add_cell_lystate": "The dataset name 'cell lystate' means cell lysis buffer. Add enough to cover the monolayer, with a fresh tip. Do not return unused buffer to the stock.",
    "transfer_cell_lystate_to_tube": "Transfer the entire lysate into a labeled microcentrifuge tube. Tilt the plate and chase residual liquid; do not leave lysate in the well.",
    "spindown": "Close the tube, balance the rotor with a tube of equal volume opposite, close the centrifuge lid, then start. Do not open the lid until the rotor has stopped. This brief spin collects liquid off the cap.",
    "aspirate_supernatant": "Wait until the rotor has stopped. Take the supernatant and leave any pellet or debris undisturbed. For the final lysate step, this tube is the collected sample.",
    "add_magnetic_beads": "Resuspend the bead stock before pipetting. Add beads into the sample tube. Beads settle quickly; do not let the pellet dry.",
    "pipetting": "Mix by slow pipetting until the suspension looks uniform, with the tip under the liquid to limit aerosols. Change tips between different reagents. If this mix is after beads, wash, ethanol, or water, name that reagent.",
    "vortex": "Cap must be fully closed. Short vortex only. For a bead tube, do not vortex so hard that the cap wets and leaks.",
    "place_in_magnetic_rack": "Seat the tube on the magnet and wait until the supernatant is clear and the beads form a pellet on the wall. Do not aspirate while the supernatant is still brown or cloudy.",
    "add_wash_buffer": "Fresh tip. Add wash buffer to the beads or onto the column membrane, not down the outside of the tube. Do not carry bead pellet into the pipette.",
    "add_70pct_ethanol": "70% ethanol is flammable; keep it off heat blocks and flames. Fresh tip. On a column, pipette onto the membrane.",
    "add_sterile_water": "This is the elution. Add sterile water to the cleared beads. After the magnet, the nucleic acid is in the supernatant, not in the bead pellet.",
    "transfer_supernatant_to_empty_tube": "With the tube still on the magnet, transfer only the clear supernatant into a new labeled tube. Leave the bead pellet behind.",
    "transfer_sample_to_8_tube_stripes": "8_tube_stripes means 8-tube PCR strips. Dispense sample to the bottom of each tube. Fresh tip. Do not touch the inner cap.",
    "transfer_pcrmix_to_8_tube_stripes": "Add PCR master mix to the bottom of the strips. Change the tip before the next reagent so primers and template stay uncontaminated.",
    "transfer_forward_primer_to_8_tube_stripes": "Add forward primer only. New tip. Do not dip the tip back into the primer stock after it has touched the reaction.",
    "transfer_reverse_primer_to_8_tube_stripes": "Add reverse primer with a new tip. Keep forward and reverse stocks separate.",
    "transfer_template_dna_to_8_tube_stripes": "Add template DNA last if it is not already in the tube, with a new tip, to the bottom of the reaction. Avoid aerosols.",
    "transfer_water_to_8_tube_stripes": "Bring the reaction to volume with molecular-grade water. New tip. Do not overfill the strip.",
    "close_8_tube_stripes_lid": "Press every cap fully shut. A loose cap opens in the cycler or leaks on the vortex.",
    "vortex_8_tube_stripes": "Confirm caps are seated, then a short vortex to mix. Do not invert an uncapped strip.",
    "spindown_8_tube_stripes": "Balance the strip rotor, close the lid, and pulse-spin so reagent is off the caps and in the bottom of the tubes.",
    "load_8_tube_stripes_to_pcr_machine": "Seat the strips in the block with caps fully closed so the heated lid can contact them. Do not start a run on an open strip.",
    "add_binding_buffer": "Add binding buffer to the sample and mix before it goes onto the column. Fresh tip.",
    "transfer_sample_tube_to_spin_column_tube": "Load the binding mixture into the spin column. Do not stab the silica membrane with the tip, and do not overfill the column.",
    "dispense_solution": "This is discarding column flow-through after the spin. Empty the collection tube into waste. Do not pour flow-through back onto the membrane.",
    "detach_spin_column_and_insert_to_new_tube": "Move the column into a clean collection tube before elution, so wash flow-through cannot touch the eluate.",
    "add_extract": "Pipette elution buffer or water onto the center of the membrane, not down the plastic wall, so the membrane is fully wetted.",
    "dispense_spin_column": "The liquid now in the clean tube is the eluate. Keep that tube and discard the column. Cap and label it.",
}

# One sentence, keyed by protocol. The old prompt listed all four endings in one
# instruction, and the model copied "column eluate" onto bead protocols.
DONE_FACT = {
    1: "Cap and label the lysate tube and keep it cold. The collected sample is the liquid in that tube.",
    2: "Cap and label the lysate tube and keep it cold. The collected sample is the liquid in that tube.",
    3: "Leave the bead pellet on the magnet. The nucleic acid is in the clear supernatant, which is now in the new tube.",
    4: "Leave the bead pellet on the magnet. The nucleic acid is in the clear supernatant, which is now in the new tube.",
    5: "Every strip cap is shut and the strips are seated in the PCR cycler. Do not open the heated lid until the run finishes.",
    6: "The eluate is the liquid in the clean collection tube. Discard the spin column.",
    7: "The eluate is the liquid in the clean collection tube. Discard the spin column.",
}

SYSTEM = """You write spoken cues for one short slice of a first-person molecular-biology protocol.
English, one or two sentences, as if through an earpiece.
Name the reagent and the one handling constraint for that step.
Do not invent volumes, incubation times, g-force, temperatures, or kit names.
Do not copy the technique note verbatim; tell the person what to do.
Dataset spelling: "lystate" means cell lysis buffer; "8_tube_stripes" means 8-tube PCR strips; "70pct" means 70%.
When the same task name has occurred before, say which occurrence this is.
Reply with one JSON object and nothing else. No markdown.
{"interrupts":[{"time_sec":0.0,"kind":"next_step","step":"<task>","text":"<spoken cue>"}]}
"""


def protocol_id_of(trial_id: str) -> int:
    parts = trial_id.split("_")
    if len(parts) < 2:
        raise ValueError(trial_id)
    return int(parts[1])


def load_annotation(path: Path) -> tuple[list[dict], list[dict]]:
    steps, atomics = [], []
    with path.open(newline="") as handle:
        for row in csv.DictReader(handle):
            rec = {
                "start": float(row["start_sec"]),
                "end": float(row["end_sec"]),
                "task": (row.get("task") or "").strip(),
                "hand": (row.get("hand_side") or "").strip(),
                "verb": (row.get("verb") or "").strip(),
                "manip": (row.get("manipulated_object") or "").strip(),
                "affected": (row.get("affected_object") or "").strip(),
            }
            if rec["task"]:
                steps.append(rec)
            elif rec["verb"]:
                atomics.append(rec)
    return steps, atomics


def atomic_line(rec: dict) -> str:
    bits = [f"{rec['start']:.3f}-{rec['end']:.3f}", rec["hand"], rec["verb"], rec["manip"]]
    if rec["affected"]:
        bits.append("-> " + rec["affected"])
    return " ".join(b for b in bits if b)


def assign_atomics(steps: list[dict], atomics: list[dict]) -> list[list[dict]]:
    grouped = [[] for _ in steps]
    for rec in atomics:
        mid = 0.5 * (rec["start"] + rec["end"])
        best_i, best_ov = None, 0.0
        for i, step in enumerate(steps):
            ov = min(rec["end"], step["end"]) - max(rec["start"], step["start"])
            if ov > best_ov:
                best_ov, best_i = ov, i
        if best_i is None:
            # Fall back to the step whose interval contains the midpoint, else the nearest step.
            for i, step in enumerate(steps):
                if step["start"] - 0.2 <= mid <= step["end"] + 0.2:
                    best_i = i
                    break
        if best_i is None and steps:
            best_i = min(range(len(steps)), key=lambda i: abs(mid - steps[i]["start"]))
        if best_i is not None:
            grouped[best_i].append(rec)
    return grouped


def divergence_index(observed: list[str], canonical: list[str]) -> int | None:
    for i, (obs, can) in enumerate(zip(observed, canonical)):
        if obs != can:
            return i
    if len(observed) != len(canonical):
        return min(len(observed), len(canonical))
    return None


def cue_time(steps: list[dict], index: int) -> float:
    if index <= 0:
        return round(steps[0]["start"], 3)
    gap = steps[index]["start"] - steps[index - 1]["end"]
    if gap >= 0.5:
        return round(steps[index - 1]["end"], 3)
    return round(steps[index]["start"], 3)


def sequence_check(observed: list[str], canonical: list[str]) -> str:
    if observed == canonical:
        return "MATCH. Observed steps are the canonical protocol, in order. Do not emit a deviation interrupt."
    lines = []
    n = max(len(observed), len(canonical))
    first = None
    for i in range(n):
        obs = observed[i] if i < len(observed) else "(missing)"
        can = canonical[i] if i < len(canonical) else "(no further canonical step)"
        if obs != can and first is None:
            first = i
            lines.append(f"  step {i + 1}: observed={obs} canonical={can}  <-- first divergence")
        elif obs != can:
            lines.append(f"  step {i + 1}: observed={obs} canonical={can}")
    where = "past the last observed step" if first is not None and first >= len(observed) else f"step index {first + 1}" if first is not None else "unknown"
    return (
        f"MISMATCH. First divergence at {where}. "
        "Emit one deviation interrupt there, and do not also emit next_step at that same time.\n"
        + "\n".join(lines)
    )


def build_prompt(trial_id: str, pid: int, steps: list[dict], grouped: list[list[dict]]) -> str:
    canonical = CANONICAL[pid]
    observed = [s["task"] for s in steps]
    canon_lines = []
    for i, task in enumerate(canonical, 1):
        tip = TECHNIQUE.get(task, "Follow this step without contaminating the next reagent.")
        canon_lines.append(f"{i}. {task} — {tip}")
    obs_lines = []
    for i, (step, acts) in enumerate(zip(steps, grouped), 1):
        tip = TECHNIQUE.get(step["task"], "")
        obs_lines.append(
            f"{i}. {step['task']}  start_sec={step['start']:.3f}  end_sec={step['end']:.3f}"
            + (f"\n   technique: {tip}" if tip else "")
        )
        show = acts[:8]
        for rec in show:
            obs_lines.append("   - " + atomic_line(rec))
        if len(acts) > len(show):
            obs_lines.append(f"   - (+{len(acts) - len(show)} more atomic actions, all consistent with this step)")
    frames_note = (
        "The images are first-person frames sampled near step boundaries. "
        "Each image is preceded by its timestamp. Use them only to confirm the vessel on the bench "
        "and to catch a real hazard. Do not move an interrupt time to match a guess from the picture."
    )
    return (
        f"TRIAL {trial_id}\n"
        f"PROTOCOL {pid}: {PROTOCOL_NAMES[pid]}\n\n"
        "CANONICAL ORDER (what a correct run must do):\n"
        + "\n".join(canon_lines)
        + "\n\nOBSERVED ACTION STEPS (what this video's annotation says happened):\n"
        + "\n".join(obs_lines)
        + "\n\nSEQUENCE CHECK:\n"
        + sequence_check(observed, canonical)
        + "\n\n"
        + frames_note
        + "\n\nReturn the JSON object now."
    )


def build_chunk_prompt(
    trial_id: str,
    pid: int,
    steps: list[dict],
    grouped: list[list[dict]],
    indices: list[int],
    diverge_at: int | None,
) -> str:
    observed = [s["task"] for s in steps]
    canonical = CANONICAL[pid]
    lines = [
        f"TRIAL {trial_id}",
        f"PROTOCOL {pid}: {PROTOCOL_NAMES[pid]}",
        f"Write exactly {len(indices)} interrupts, one per step below, in this order.",
        "Copy time_sec and step exactly. Write only the spoken text.",
        "kind is next_step, unless the line says DEVIATION, in which case kind is deviation.",
        "Do not add a completion line in this slice.",
        "",
    ]
    for n, i in enumerate(indices, 1):
        step = steps[i]
        seen = sum(1 for s in steps[: i + 1] if s["task"] == step["task"])
        total = sum(1 for s in steps if s["task"] == step["task"])
        kind = "deviation" if diverge_at == i else "next_step"
        tip = TECHNIQUE.get(step["task"], "Do not carry this reagent into the next container.")
        prev = steps[i - 1]["task"] if i else "(start of the protocol)"
        nxt = steps[i + 1]["task"] if i + 1 < len(steps) else "(last step)"
        lines.append(
            f"{n}. time_sec={cue_time(steps, i):.3f} step={step['task']} kind={kind} "
            f"(occurrence {seen} of {total}; after {prev}; before {nxt})"
        )
        lines.append(f"   constraint: {tip}")
        if kind == "deviation":
            can = canonical[i] if i < len(canonical) else "(protocol already finished)"
            lines.append(
                f"   DEVIATION: canonical step here is {can}, but the video shows {observed[i]}. "
                "Say what the protocol required and what to do instead."
            )
        for rec in grouped[i][:4]:
            lines.append("   - " + atomic_line(rec))
    if diverge_at is not None and diverge_at >= len(steps) and indices and indices[-1] == len(steps) - 1:
        missing = canonical[len(steps)] if len(steps) < len(canonical) else "(extra steps)"
        lines.append(
            f"The video ended before canonical step {missing}. "
            "On the last item, kind=deviation, and say that step is still required."
        )
    lines.append("\nReturn the JSON object now.")
    return "\n".join(lines)


def build_done_prompt(trial_id: str, pid: int, steps: list[dict]) -> str:
    last = steps[-1]
    return (
        f"TRIAL {trial_id}\n"
        f"PROTOCOL {pid}: {PROTOCOL_NAMES[pid]}\n"
        f"The last step was {last['task']} and it ended at {last['end']:.3f} s.\n"
        "Write exactly one interrupt.\n"
        f"time_sec={last['end']:.3f} step={last['task']} kind=done\n"
        f"The only fact to convey: {DONE_FACT[pid]}\n"
        "One spoken sentence. Do not mention a column, beads, a cycler, or lysate "
        "unless that fact mentions it.\n"
        "Return the JSON object now."
    )


def sample_frames(video: Path, steps: list[dict], out_dir: Path, indices: list[int] | None = None) -> list[tuple[int, float, Path]]:
    if not steps:
        return []
    idxs = list(range(len(steps))) if indices is None else list(indices)
    out_dir.mkdir(parents=True, exist_ok=True)
    cap = cv2.VideoCapture(str(video))
    if not cap.isOpened():
        return []
    fps = cap.get(cv2.CAP_PROP_FPS) or 30.0
    nframes = cap.get(cv2.CAP_PROP_FRAME_COUNT) or 0
    duration = nframes / fps if fps else 0
    saved = []
    for i in idxs:
        step = steps[i]
        t = min(step["start"] + 0.4, max(step["start"], 0.5 * (step["start"] + step["end"])))
        if duration:
            t = min(t, max(0.0, duration - 0.05))
        cap.set(cv2.CAP_PROP_POS_MSEC, t * 1000.0)
        ok, frame = cap.read()
        if not ok:
            continue
        frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        path = out_dir / f"f{i:02d}_{t:.2f}.jpg"
        Image.fromarray(frame).save(path, quality=85)
        saved.append((i, t, path))
    cap.release()
    return saved


def extract_json(text: str):
    raw = text.strip()
    raw = re.sub(r"^```(?:json)?\s*", "", raw)
    raw = re.sub(r"\s*```$", "", raw)
    try:
        return json.loads(raw)
    except json.JSONDecodeError:
        start, end = raw.find("{"), raw.rfind("}")
        if start >= 0 and end > start:
            return json.loads(raw[start : end + 1])
        start, end = raw.find("["), raw.rfind("]")
        if start >= 0 and end > start:
            return json.loads(raw[start : end + 1])
        raise


def normalize(obj: dict, trial_id: str, pid: int) -> dict:
    interrupts = []
    for item in obj.get("interrupts") or []:
        if not isinstance(item, dict):
            continue
        kind = str(item.get("kind") or "").strip()
        if kind not in {"next_step", "deviation", "safety", "done"}:
            continue
        text = str(item.get("text") or "").strip()
        if not text:
            continue
        try:
            t = round(float(item.get("time_sec")), 3)
        except (TypeError, ValueError):
            continue
        interrupts.append(
            {
                "time_sec": t,
                "kind": kind,
                "step": str(item.get("step") or "").strip(),
                "text": text,
            }
        )
    interrupts.sort(key=lambda x: (x["time_sec"], x["kind"] != "deviation"))
    # One utterance per timestamp: a deviation replaces a cue at the same moment.
    dedup = []
    seen = set()
    for item in interrupts:
        key = item["time_sec"]
        if key in seen:
            continue
        seen.add(key)
        dedup.append(item)
    return {"trial_id": trial_id, "protocol_id": pid, "interrupts": dedup}


def load_model(model_id: str):
    processor = AutoProcessor.from_pretrained(model_id, trust_remote_code=True)
    model = Qwen2_5_VLForConditionalGeneration.from_pretrained(
        model_id,
        torch_dtype=torch.bfloat16,
        device_map="auto",
        attn_implementation="sdpa",
    )
    model.eval()
    return processor, model


@torch.inference_mode()
def generate(processor, model, prompt: str, frames: list[tuple[float, Path]], max_new_tokens: int) -> str:
    content = []
    max_pixels = 128 * 28 * 28
    for t, path in frames:
        content.append({"type": "text", "text": f"Frame at t={t:.3f}s."})
        content.append({"type": "image", "image": str(path), "max_pixels": max_pixels})
    content.append({"type": "text", "text": prompt})
    messages = [
        {"role": "system", "content": SYSTEM},
        {"role": "user", "content": content},
    ]
    chat = processor.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
    image_inputs, video_inputs = process_vision_info(messages)
    kwargs = {"text": [chat], "return_tensors": "pt"}
    if image_inputs:
        kwargs["images"] = image_inputs
    if video_inputs:
        kwargs["videos"] = video_inputs
    inputs = processor(**kwargs)
    device = model.device
    inputs = {k: v.to(device) if torch.is_tensor(v) else v for k, v in inputs.items()}
    out = model.generate(**inputs, max_new_tokens=max_new_tokens, do_sample=False)
    gen = out[:, inputs["input_ids"].shape[1] :]
    return processor.batch_decode(gen, skip_special_tokens=True)[0].strip()


def texts_from_raw(raw: str) -> list[str]:
    obj = extract_json(raw)
    if isinstance(obj, list):
        items = obj
    elif isinstance(obj, dict):
        items = obj.get("interrupts")
        if items is None:
            items = [obj]
    else:
        items = []
    texts = []
    for item in items or []:
        if isinstance(item, dict) and str(item.get("text") or "").strip():
            texts.append(str(item["text"]).strip())
    return texts


def annotate_trial(processor, model, trial_id: str, pid: int, steps, grouped, frames, max_new_tokens: int) -> dict:
    by_index = {i: (t, path) for i, t, path in frames}
    observed = [s["task"] for s in steps]
    diverge_at = divergence_index(observed, CANONICAL[pid])
    interrupts = []
    chunk = 4
    for start in range(0, len(steps), chunk):
        indices = list(range(start, min(start + chunk, len(steps))))
        prompt = build_chunk_prompt(trial_id, pid, steps, grouped, indices, diverge_at)
        chunk_frames = [(by_index[i][0], by_index[i][1]) for i in indices if i in by_index]
        texts: list[str] = []
        for attempt in range(2):
            raw = generate(processor, model, prompt, chunk_frames, max_new_tokens)
            try:
                texts = texts_from_raw(raw)
            except json.JSONDecodeError:
                texts = []
            if len(texts) >= len(indices):
                break
            prompt += (
                f"\n\nYour previous reply had {len(texts)} cues. "
                f"Return all {len(indices)} steps, in order."
            )
        for n, i in enumerate(indices):
            step = steps[i]
            kind = "next_step"
            if diverge_at == i or (diverge_at is not None and diverge_at >= len(steps) and i == len(steps) - 1):
                kind = "deviation"
            if n < len(texts):
                text = texts[n]
            else:
                text = TECHNIQUE.get(step["task"], f"Do {step['task'].replace('_', ' ')} now.")
                print(f"[FALLBACK] {trial_id} step {i} {step['task']}", flush=True)
            interrupts.append(
                {
                    "time_sec": cue_time(steps, i),
                    "kind": kind,
                    "step": step["task"],
                    "text": text,
                }
            )
    done_raw = generate(processor, model, build_done_prompt(trial_id, pid, steps), [], 200)
    try:
        done_texts = texts_from_raw(done_raw)
    except json.JSONDecodeError:
        done_texts = []
    done_text = done_texts[0] if done_texts else DONE_FACT[pid]
    if not done_texts:
        print(f"[FALLBACK] {trial_id} done", flush=True)
    interrupts.append(
        {
            "time_sec": round(steps[-1]["end"], 3),
            "kind": "done",
            "step": steps[-1]["task"],
            "text": done_text,
        }
    )
    interrupts.sort(key=lambda x: (x["time_sec"], x["kind"] == "done"))
    return {
        "trial_id": trial_id,
        "protocol_id": pid,
        "protocol_name": PROTOCOL_NAMES[pid],
        "n_frames": len(frames),
        "interrupts": interrupts,
    }


def iter_trials(ann_dir: Path, only: set[str] | None) -> list[Path]:
    files = sorted(ann_dir.glob("P*.txt"))
    if only:
        files = [p for p in files if p.stem in only]
    return files


def already_done(path: Path) -> bool:
    """A one-line file is a collapsed generation, not a finished annotation."""
    if not path.exists():
        return False
    try:
        obj = json.loads(path.read_text())
    except json.JSONDecodeError:
        return False
    interrupts = obj.get("interrupts")
    if not isinstance(interrupts, list):
        return False
    return len(interrupts) >= 3


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--ann-dir", type=Path, required=True)
    parser.add_argument("--video-dir", type=Path, required=True)
    parser.add_argument("--out-dir", type=Path, required=True)
    parser.add_argument("--model", default="Qwen/Qwen2.5-VL-72B-Instruct")
    parser.add_argument("--max-frames", type=int, default=12)
    parser.add_argument("--max-new-tokens", type=int, default=1800)
    parser.add_argument("--trials", default="", help="Comma-separated trial ids. Default: all.")
    args = parser.parse_args()

    only = {t.strip() for t in args.trials.split(",") if t.strip()} or None
    trials = iter_trials(args.ann_dir, only)
    args.out_dir.mkdir(parents=True, exist_ok=True)
    frame_root = args.out_dir / "_frames"
    print(f"[INFO] {len(trials)} trials", flush=True)

    pending = [p for p in trials if not already_done(args.out_dir / f"{p.stem}.json")]
    print(f"[INFO] pending {len(pending)} (skip {len(trials) - len(pending)} done)", flush=True)
    if not pending:
        return

    processor, model = load_model(args.model)
    jsonl_path = args.out_dir / "interrupts.jsonl"
    with jsonl_path.open("a") as jsonl:
        for i, ann in enumerate(pending, 1):
            trial_id = ann.stem
            out_path = args.out_dir / f"{trial_id}.json"
            try:
                pid = protocol_id_of(trial_id)
                if pid not in CANONICAL:
                    raise KeyError(f"unknown protocol {pid}")
                steps, atomics = load_annotation(ann)
                if not steps:
                    raise RuntimeError(f"no protocol steps in {ann}")
                grouped = assign_atomics(steps, atomics)
                video = args.video_dir / f"{trial_id}.mp4"
                frames = sample_frames(video, steps, frame_root / trial_id)
                obj = annotate_trial(
                    processor, model, trial_id, pid, steps, grouped, frames, args.max_new_tokens
                )
                payload = json.dumps(obj, ensure_ascii=False, indent=2)
                out_path.write_text(payload + "\n")
                jsonl.write(json.dumps(obj, ensure_ascii=False) + "\n")
                jsonl.flush()
                print(
                    f"[OK] {i}/{len(pending)} {trial_id} interrupts={len(obj['interrupts'])} frames={len(frames)}",
                    flush=True,
                )
            except Exception:
                err = traceback.format_exc()
                (args.out_dir / f"{trial_id}.error.txt").write_text(err)
                print(f"[FAIL] {trial_id}\n{err}", flush=True)


if __name__ == "__main__":
    main()
